# 示例配置（复制为 settings.yaml 后再按需修改）
# - LINK：友链页来源（按 rules.yaml 的选择器抽取）
# - SETTINGS_FRIENDS_LINKS：静态补充（可选），支持自定义 feed_suffix
# - SIMPLE_MODE：启用后可通过 -export 导出 data.json（极简模式）
# - LOG_*：控制日志级别/格式/语言/颜色

LINK:
  - type: page            # 友链页来源类型：page
    url: https://your-site.example.com/friends   # 你的友链页地址
    theme: default        # 对应 rules.yaml 中的预设名称（default/clarity 等）

# 可选：手动补充固定朋友（未从页面发现时也会纳入处理）
#SETTINGS_FRIENDS_LINKS:
#  - name: "示例博客"
#    link: "https://example.com/"
#    avatar: "https://example.com/avatar.png"
#    feed_suffix: "/atom.xml"   # 可选：用于提升订阅发现命中率

MAX_POSTS_NUM: 10          # 每个朋友最多抓取文章数（0 表示不限制）
OUTDATE_CLEAN: 90          # 过期清理天数
SIMPLE_MODE: true          # 是否启用极简导出

DATABASE:
  type: sqlite
  dsn: ./data.db

CONCURRENCY:
  fetch: 8
  retry: 2

PROXY:
  http: ""                # 如 http://127.0.0.1:7890
  https: ""
LOG_LEVEL: info            # debug|info|warn|error|none
LOG_FORMAT: pretty         # text|json|pretty
LOG_LOCALE: zh-CN          # zh-CN|en
LOG_COLOR: auto            # auto|always|never
