name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download deps
        run: go mod download

      - name: Run unit tests (with coverage)
        env:
          GOCACHE: .gocache
        run: |
          mkdir -p .gocache
          go test -coverpkg=./... ./tests -count=1 -race -coverprofile=coverage.out -v

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

