name: Build & Export Data

on:
  # 每 6 小时运行一次（UTC 00:00/06:00/12:00/18:00）
  schedule:
    - cron: '0 */6 * * *'
  # 支持手动触发（便于临时导出或验证）
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: export-data
  cancel-in-progress: true

jobs:
  build-and-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download deps
        run: go mod download

      - name: Build binary
        run: go build -o cof .

      - name: Export JSON
        env:
          GOCACHE: ${{ github.workspace }}/.gocache
        run: |
          mkdir -p "$GOCACHE"
          ./cof -config settings.yaml -rules rules.yaml -export data.json

      - name: Prepare publish dir
        run: |
          rm -rf _export
          mkdir -p _export
          mv -f data.json _export/data.json

      - name: Publish to data branch (only JSON)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -euo pipefail
          cd _export
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b data
          git add data.json
          git commit -m "chore(data): update data.json"
          git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" data

